version: "3"
services:
    kmysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: insight
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
         - db_data:/var/lib/mysql
    kapp:
        build: .
        links:
            - kmysql:db
        ports:
            - 8080:8080
        environment:
            DB_HOST: kmysql:3306
            DB_USER: user
            DB_PASSWORD: user
            DB_NAME: insight
volumes:
    db_data: {}